name: volufriend
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.1.2 <4.0.0'
dependencies: 

  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  badges: ^3.0.2
  flutter_screenutil: ^5.0.0+2 # Add flutter_screenutil package
  table_calendar: ^3.1.2
  firebase_messaging: ^14.0.0
  firebase_messaging_platform_interface: ^4.5.37
  pdf: ^3.6.0  # Check for the latest version on pub.dev
  printing: ^5.10.0  # Check for the latest version on pub.dev
  flutter_typeahead: ^4.0.0
  folding_cell: ^1.0.0
  image_picker: ^0.8.4+4
  percent_indicator: ^4.0.2 
  image_field: ^0.0.2
  multi_dropdown: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  sizer: ^2.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  flutter_switch: ^0.3.2
  country_pickers: ^3.0.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.5.8
  dotted_border: ^2.1.0
  calendar_date_picker2: ^1.1.5
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBlack.ttf
          weight: 900
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsLightItalic.ttf
          weight: 300
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Playfair Display
      fonts: 
        - asset: assets/fonts/PlayfairDisplayRegular.ttf
          weight: 400
