// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBb7Zb5NDZjLISAPeYe1SlqR8-2xhcWNc',
    appId: '1:810082152615:android:236f2ac4e770d58c2eeb82',
    messagingSenderId: '810082152615',
    projectId: 'volufriend',
    databaseURL: 'https://volufriend-default-rtdb.firebaseio.com',
    storageBucket: 'volufriend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB126e4hSrfCLs40TrO3R-NGREqLnq2Rgg',
    appId: '1:810082152615:ios:d3c94a57a15388aa2eeb82',
    messagingSenderId: '810082152615',
    projectId: 'volufriend',
    databaseURL: 'https://volufriend-default-rtdb.firebaseio.com',
    storageBucket: 'volufriend.appspot.com',
    iosBundleId: 'com.volufriend.app.testProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQRZl-CMUKIAo9LXF4cBKYpHg6Ku1x4M',
    appId: '1:810082152615:web:e14663e45c8c15382eeb82',
    messagingSenderId: '810082152615',
    projectId: 'volufriend',
    authDomain: 'volufriend.firebaseapp.com',
    databaseURL: 'https://volufriend-default-rtdb.firebaseio.com',
    storageBucket: 'volufriend.appspot.com',
    measurementId: 'G-1BS8J5XMQ2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB126e4hSrfCLs40TrO3R-NGREqLnq2Rgg',
    appId: '1:810082152615:ios:99f46938e72620fe2eeb82',
    messagingSenderId: '810082152615',
    projectId: 'volufriend',
    databaseURL: 'https://volufriend-default-rtdb.firebaseio.com',
    storageBucket: 'volufriend.appspot.com',
    iosBundleId: 'com.volufriend.volufriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvQRZl-CMUKIAo9LXF4cBKYpHg6Ku1x4M',
    appId: '1:810082152615:web:495d781a27f198582eeb82',
    messagingSenderId: '810082152615',
    projectId: 'volufriend',
    authDomain: 'volufriend.firebaseapp.com',
    databaseURL: 'https://volufriend-default-rtdb.firebaseio.com',
    storageBucket: 'volufriend.appspot.com',
    measurementId: 'G-QZQ7PMVCVJ',
  );

}